# Generated by Django 6.0.2 on 2026-02-18 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0002_department_rename_created_at_employee_joined_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Kehadiran', 'verbose_name_plural': 'Log Kehadiran'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departemen', 'verbose_name_plural': 'Daftar Departemen'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Karyawan', 'verbose_name_plural': 'Daftar Karyawan'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Masuk'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Jam Pulang'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd_app.employee', verbose_name='Karyawan'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Hadir', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Departemen'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrd_app.department', verbose_name='Departemen'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nomor Induk Karyawan (NIK)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='No. Telepon'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Akun User'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
