# Generated by Django 6.0.2 on 2026-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0003_alter_attendance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lat_in',
            field=models.FloatField(blank=True, null=True, verbose_name='Lat Masuk'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lat_out',
            field=models.FloatField(blank=True, null=True, verbose_name='Lat Pulang'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lon_in',
            field=models.FloatField(blank=True, null=True, verbose_name='Lon Masuk'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lon_out',
            field=models.FloatField(blank=True, null=True, verbose_name='Lon Pulang'),
        ),
    ]
