# Generated by Django 6.0.2 on 2026-02-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd_app', '0004_attendance_lat_in_attendance_lat_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo_in',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/%Y/%m/%d/', verbose_name='Foto Masuk'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='photo_out',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/%Y/%m/%d/', verbose_name='Foto Pulang'),
        ),
    ]
